name: Build Windows App (Unpacked via electron-packager)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm i

      - name: Pack (electron-packager)
        run: npx electron-packager . QuietWidget --platform=win32 --arch=x64 --out release --overwrite --asar

      - name: Normalize output folder name
        shell: pwsh
        run: |
          $out = Get-ChildItem -Path release -Directory | Select-Object -First 1
          if (-not $out) { throw "No output dir found under 'release'." }

          $newName = 'QuietWidget-win64'
          $dest = Join-Path $out.Parent.FullName $newName

          if (Test-Path $dest) { Remove-Item -Recurse -Force $dest }
          Rename-Item -Path $out.FullName -NewName $newName

      - name: Upload artifact (folder, not zipped)
        uses: actions/upload-artifact@v4
        with:
          name: QuietWidget-win64
          path: release/QuietWidget-win64
